name: project_structure_temp
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  dio: ^5.8.0+1
  intl: ^0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.2
  connectivity_plus: ^6.1.4
  pretty_dio_logger: ^1.4.0
  # Icons
  cupertino_icons: ^1.0.8
  # State Management
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/icons/
    - assets/logos/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
